### ISSUE TITLE
Review wording of requirement 5 (dual notification)

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/matchmakerexchange.github.io#19] opened 2015-10-06 04:21 UTC
From @Relequestual:

> I think we may need to review the wording of requirement number 5!
> 
> During user queries, enable dual notification of data requester (i.e. the querier) and prior data depositor (i.e. the queried) including sharing the identities and contact information for each
> 
> Currently within Decipher, the data depositor is only notified if the querier decides to follow up on the request (As in, chooses to make contact). In addition, Decipher does not make the identity of the data depositor known. It is up to the original depositor of Decipher data to decide if they wish to responde to any contact request. This is the same way we handle contact requests made by unauthenticated user looking at public consented data on Decipher.

**Comment by Relequestual** [comment] 2016-09-21 15:14
Anyone remember when this document was updated to include that phrasing?

@jxchong looks like I already raised this issue.
I wonder if a repo for simply keeping track of policy issues would be useful.

**Comment by jxchong** [comment] 2016-09-21 15:32
Yes this is one of the things that really confused/perplexed us when we were reviewing the materials to learn how to join MME.

The problem is that if you change requirement number 5 to allow for using a proxy to hide the identify of the original depositor (and right now requirement number 5 is a problem because PhenomeCentral and Decipher are using proxies despite it explicitly being forbidden), then you need to come up with policies that specify the conditions the proxy is allowed to impose before passing on the info for the original depositor. 

For example:

* is proxy allowed to tell original depositor about the contact without telling the querier? (I would think no!)
* is proxy allowed to place conditions on putting the querier in contact with original depositor? (example: can proxy say "I'll only put you in contact if you agree to give us [the proxy] co-authorship"?) Again, I don't think this should be allowed.
* if there are conditions "checking to make sure that there is a clear research question + legit clinician/researcher + candidate gene)" in order to pass on the message, that should be something that's stated publicly on the MME site or in the match response so that it can be provided to the user.

**Comment by Relequestual** [comment] 2016-09-22 08:34
> is proxy allowed to tell original depositor about the contact without telling the querier? (I would think no!)
Actually, that's exactly how DECIPHER currently works. We leave it up to the origninal depositor to decide if they want to respond to the contact request or not, and we do not (and cannot) divulge the depositors identity.

**Comment by Relequestual** [comment] 2016-09-22 08:35
@jxchong would you like to further explain for the point of record your experience with GeneDX, as per our discussion yesterday?

I'll email the general group email and direct them to this issue.

**Comment by dazzariti** [comment] 2017-08-18 21:08
Resolving issue #48 (posting updated service requirements) will also resolve this issue.

**Closed** 2017-09-27 23:22 UTC
